module.exports = {
	important: true,
	corePlugins: {
		// We have our own preflight styles
		preflight: false,
	},
	content: [
		'./assets/**/*.{vue,js,css}',
		'./components/**/*.{vue,js,ts}',
		'./layouts/**/*.vue',
		'./pages/**/*.vue',
		'./doctypes/**/*.vue',
		'./composables/**/*.{js,ts}',
		'./plugins/**/*.{js,ts}',
		'./App.{js,ts,vue}',
		'./app.{js,ts,vue}',
		'./Error.{js,ts,vue}',
		'./error.{js,ts,vue}',
		'./server/**/*.{js,ts}',
	],

	theme: {
		accentColor: ({ theme }) => ({
			...theme('colors'),
			auto: 'auto',
		}),
		animation: {
			none: 'none',
			// Removed some values
		},
		aria: {
			checked: 'checked="true"',
			disabled: 'disabled="true"',
			expanded: 'expanded="true"',
			hidden: 'hidden="true"',
			pressed: 'pressed="true"',
			readonly: 'readonly="true"',
			required: 'required="true"',
			selected: 'selected="true"',
		},
		aspectRatio: {
			auto: 'auto',
			1: '1 / 1',
			'16/9': '16 / 9',
			// Renamed some values
		},
		backdropBlur: ({ theme }) => theme('blur'),
		backdropBrightness: ({ theme }) => theme('brightness'),
		backdropContrast: ({ theme }) => theme('contrast'),
		backdropGrayscale: ({ theme }) => theme('grayscale'),
		backdropHueRotate: ({ theme }) => theme('hueRotate'),
		backdropInvert: ({ theme }) => theme('invert'),
		backdropOpacity: ({ theme }) => theme('opacity'),
		backdropSaturate: ({ theme }) => theme('saturate'),
		backdropSepia: ({ theme }) => theme('sepia'),
		backgroundColor: ({ theme }) => theme('colors'),
		backgroundImage: {
			none: 'none',
			// Removed some values
		},
		backgroundOpacity: ({ theme }) => theme('opacity'),
		backgroundPosition: {
			bottom: 'bottom',
			center: 'center',
			left: 'left',
			'left-bottom': 'left bottom',
			'left-top': 'left top',
			right: 'right',
			'right-bottom': 'right bottom',
			'right-top': 'right top',
			top: 'top',
		},
		backgroundSize: {
			auto: 'auto',
			cover: 'cover',
			contain: 'contain',
		},
		blur: {
			0: '0',
			none: '0',
			// Removed some values
		},
		borderColor: ({ theme }) => ({
			...theme('colors'),
			DEFAULT: theme('currentColor'),
			// Altered some values
		}),
		borderOpacity: ({ theme }) => theme('opacity'),
		borderRadius: {
			none: '0px',
			full: '9999px',
			// Removed some values
		},
		borderSpacing: ({ theme }) => ({
			...theme('spacing'),
		}),
		borderWidth: {
			DEFAULT: '1px',
			0: '0px',
			2: '2px',
			// Removed some values
		},
		boxShadow: {
			none: 'none',
			// Removed some values
		},
		boxShadowColor: ({ theme }) => theme('colors'),
		brightness: {
			0: '0',
			50: '.5',
			75: '.75',
			90: '.9',
			95: '.95',
			100: '1',
			105: '1.05',
			110: '1.1',
			125: '1.25',
			150: '1.5',
			200: '2',
		},
		caretColor: ({ theme }) => theme('colors'),
		colors: ({ colors }) => ({
			inherit: colors.inherit,
			current: colors.current,
			transparent: colors.transparent,
			black: colors.black,
			white: colors.white,
			// Removed some values
		}),
		columns: {
			auto: 'auto',
			1: '1',
			2: '2',
			3: '3',
			4: '4',
			5: '5',
			6: '6',
			7: '7',
			8: '8',
			9: '9',
			10: '10',
			11: '11',
			12: '12',
			// Removed some values
		},
		container: {},
		content: {
			none: 'none',
		},
		contrast: {
			0: '0',
			50: '.5',
			75: '.75',
			100: '1',
			125: '1.25',
			150: '1.5',
			200: '2',
		},
		cursor: {
			auto: 'auto',
			default: 'default',
			pointer: 'pointer',
			wait: 'wait',
			text: 'text',
			move: 'move',
			help: 'help',
			'not-allowed': 'not-allowed',
			none: 'none',
			'context-menu': 'context-menu',
			progress: 'progress',
			cell: 'cell',
			crosshair: 'crosshair',
			'vertical-text': 'vertical-text',
			alias: 'alias',
			copy: 'copy',
			'no-drop': 'no-drop',
			grab: 'grab',
			grabbing: 'grabbing',
			'all-scroll': 'all-scroll',
			'col-resize': 'col-resize',
			'row-resize': 'row-resize',
			'n-resize': 'n-resize',
			'e-resize': 'e-resize',
			's-resize': 's-resize',
			'w-resize': 'w-resize',
			'ne-resize': 'ne-resize',
			'nw-resize': 'nw-resize',
			'se-resize': 'se-resize',
			'sw-resize': 'sw-resize',
			'ew-resize': 'ew-resize',
			'ns-resize': 'ns-resize',
			'nesw-resize': 'nesw-resize',
			'nwse-resize': 'nwse-resize',
			'zoom-in': 'zoom-in',
			'zoom-out': 'zoom-out',
		},
		divideColor: ({ theme }) => theme('borderColor'),
		divideOpacity: ({ theme }) => theme('borderOpacity'),
		divideWidth: ({ theme }) => theme('borderWidth'),
		dropShadow: {
			none: '0 0 #0000',
			// Removed some values
		},
		fill: ({ theme }) => ({
			none: 'none',
			...theme('colors'),
		}),
		flex: {
			1: '1 1 0%',
			auto: '1 1 auto',
			initial: '0 1 auto',
			none: 'none',
		},
		flexBasis: ({ theme }) => ({
			auto: 'auto',
			...theme('spacing'),
			'1/2': '50%',
			'1/3': '33.333333%',
			'2/3': '66.666667%',
			'1/4': '25%',
			'2/4': '50%',
			'3/4': '75%',
			'1/5': '20%',
			'2/5': '40%',
			'3/5': '60%',
			'4/5': '80%',
			'1/6': '16.666667%',
			'2/6': '33.333333%',
			'3/6': '50%',
			'4/6': '66.666667%',
			'5/6': '83.333333%',
			'1/12': '8.333333%',
			'2/12': '16.666667%',
			'3/12': '25%',
			'4/12': '33.333333%',
			'5/12': '41.666667%',
			'6/12': '50%',
			'7/12': '58.333333%',
			'8/12': '66.666667%',
			'9/12': '75%',
			'10/12': '83.333333%',
			'11/12': '91.666667%',
			full: '100%',
		}),
		flexGrow: {
			0: '0',
			DEFAULT: '1',
		},
		flexShrink: {
			0: '0',
			DEFAULT: '1',
		},
		fontFamily: {
			sans: [
				'ui-sans-serif',
				'system-ui',
				'-apple-system',
				'BlinkMacSystemFont',
				'"Segoe UI"',
				'Roboto',
				'"Helvetica Neue"',
				'Arial',
				'"Noto Sans"',
				'sans-serif',
				'"Apple Color Emoji"',
				'"Segoe UI Emoji"',
				'"Segoe UI Symbol"',
				'"Noto Color Emoji"',
			],
			serif: [
				'ui-serif',
				'Georgia',
				'Cambria',
				'"Times New Roman"',
				'Times',
				'serif',
			],
			mono: [
				'ui-monospace',
				'SFMono-Regular',
				'Menlo',
				'Monaco',
				'Consolas',
				'"Liberation Mono"',
				'"Courier New"',
				'monospace',
			],
		},
		fontSize: {
			// Removed some values
		},
		fontWeight: {
			thin: '100',
			extralight: '200',
			light: '300',
			normal: '400',
			medium: '500',
			semibold: '600',
			bold: '700',
			extrabold: '800',
			black: '900',
		},
		gap: ({ theme }) => theme('spacing'),
		gradientColorStops: ({ theme }) => theme('colors'),
		grayscale: {
			0: '0',
			DEFAULT: '100%',
		},
		gridAutoColumns: {
			auto: 'auto',
			min: 'min-content',
			max: 'max-content',
			fr: 'minmax(0, 1fr)',
		},
		gridAutoRows: {
			auto: 'auto',
			min: 'min-content',
			max: 'max-content',
			fr: 'minmax(0, 1fr)',
		},
		gridColumn: {
			auto: 'auto',
			'span-1': 'span 1 / span 1',
			'span-2': 'span 2 / span 2',
			'span-3': 'span 3 / span 3',
			'span-4': 'span 4 / span 4',
			'span-5': 'span 5 / span 5',
			'span-6': 'span 6 / span 6',
			'span-7': 'span 7 / span 7',
			'span-8': 'span 8 / span 8',
			'span-9': 'span 9 / span 9',
			'span-10': 'span 10 / span 10',
			'span-11': 'span 11 / span 11',
			'span-12': 'span 12 / span 12',
			'span-full': '1 / -1',
		},
		gridColumnEnd: {
			auto: 'auto',
			1: '1',
			2: '2',
			3: '3',
			4: '4',
			5: '5',
			6: '6',
			7: '7',
			8: '8',
			9: '9',
			10: '10',
			11: '11',
			12: '12',
			13: '13',
		},
		gridColumnStart: {
			auto: 'auto',
			1: '1',
			2: '2',
			3: '3',
			4: '4',
			5: '5',
			6: '6',
			7: '7',
			8: '8',
			9: '9',
			10: '10',
			11: '11',
			12: '12',
			13: '13',
		},
		gridRow: {
			auto: 'auto',
			'span-1': 'span 1 / span 1',
			'span-2': 'span 2 / span 2',
			'span-3': 'span 3 / span 3',
			'span-4': 'span 4 / span 4',
			'span-5': 'span 5 / span 5',
			'span-6': 'span 6 / span 6',
			'span-full': '1 / -1',
		},
		gridRowEnd: {
			auto: 'auto',
			1: '1',
			2: '2',
			3: '3',
			4: '4',
			5: '5',
			6: '6',
			7: '7',
		},
		gridRowStart: {
			auto: 'auto',
			1: '1',
			2: '2',
			3: '3',
			4: '4',
			5: '5',
			6: '6',
			7: '7',
		},
		gridTemplateColumns: {
			none: 'none',
			1: 'repeat(1, minmax(0, 1fr))',
			2: 'repeat(2, minmax(0, 1fr))',
			3: 'repeat(3, minmax(0, 1fr))',
			4: 'repeat(4, minmax(0, 1fr))',
			5: 'repeat(5, minmax(0, 1fr))',
			6: 'repeat(6, minmax(0, 1fr))',
			7: 'repeat(7, minmax(0, 1fr))',
			8: 'repeat(8, minmax(0, 1fr))',
			9: 'repeat(9, minmax(0, 1fr))',
			10: 'repeat(10, minmax(0, 1fr))',
			11: 'repeat(11, minmax(0, 1fr))',
			12: 'repeat(12, minmax(0, 1fr))',
		},
		gridTemplateRows: {
			none: 'none',
			1: 'repeat(1, minmax(0, 1fr))',
			2: 'repeat(2, minmax(0, 1fr))',
			3: 'repeat(3, minmax(0, 1fr))',
			4: 'repeat(4, minmax(0, 1fr))',
			5: 'repeat(5, minmax(0, 1fr))',
			6: 'repeat(6, minmax(0, 1fr))',
		},
		height: ({ theme }) => ({
			auto: 'auto',
			...theme('spacing'),
			'1/2': '50%',
			'1/3': '33.333333%',
			'2/3': '66.666667%',
			'1/4': '25%',
			'2/4': '50%',
			'3/4': '75%',
			'1/5': '20%',
			'2/5': '40%',
			'3/5': '60%',
			'4/5': '80%',
			'1/6': '16.666667%',
			'2/6': '33.333333%',
			'3/6': '50%',
			'4/6': '66.666667%',
			'5/6': '83.333333%',
			full: '100%',
			screen: '100vh',
			min: 'min-content',
			max: 'max-content',
			fit: 'fit-content',
		}),
		hueRotate: {
			0: '0deg',
			15: '15deg',
			30: '30deg',
			60: '60deg',
			90: '90deg',
			180: '180deg',
		},
		inset: ({ theme }) => ({
			auto: 'auto',
			...theme('spacing'),
			'1/2': '50%',
			'1/3': '33.333333%',
			'2/3': '66.666667%',
			'1/4': '25%',
			'2/4': '50%',
			'3/4': '75%',
			full: '100%',
		}),
		invert: {
			0: '0',
			DEFAULT: '100%',
		},
		keyframes: {
			// Removed some values
		},
		letterSpacing: {
			normal: '0em',
			// Removed and renamed some values
		},
		lineHeight: {
			none: '1',
			normal: '1.5',
			// Removed some values
		},
		listStyleType: {
			none: 'none',
			disc: 'disc',
			decimal: 'decimal',
		},
		margin: ({ theme }) => ({
			auto: 'auto',
			...theme('spacing'),
		}),
		maxHeight: ({ theme }) => ({
			...theme('spacing'),
			none: 'none',
			full: '100%',
			screen: '100vh',
			min: 'min-content',
			max: 'max-content',
			fit: 'fit-content',
		}),
		maxWidth: ({ theme, breakpoints }) => ({
			none: 'none',
			0: '0px',
			full: '100%',
			screen: '100vw',
			min: 'min-content',
			max: 'max-content',
			fit: 'fit-content',
			...breakpoints(theme('screens')),
			// Removed some values
		}),
		minHeight: {
			0: '0px',
			full: '100%',
			screen: '100vh',
			min: 'min-content',
			max: 'max-content',
			fit: 'fit-content',
		},
		minWidth: {
			0: '0px',
			full: '100%',
			screen: '100vw',
			min: 'min-content',
			max: 'max-content',
			fit: 'fit-content',
		},
		objectPosition: {
			bottom: 'bottom',
			center: 'center',
			left: 'left',
			'left-bottom': 'left bottom',
			'left-top': 'left top',
			right: 'right',
			'right-bottom': 'right bottom',
			'right-top': 'right top',
			top: 'top',
		},
		opacity: {
			0: '0',
			5: '0.05',
			10: '0.1',
			20: '0.2',
			25: '0.25',
			30: '0.3',
			40: '0.4',
			50: '0.5',
			60: '0.6',
			70: '0.7',
			75: '0.75',
			80: '0.8',
			90: '0.9',
			95: '0.95',
			100: '1',
		},
		order: {
			first: '-9999',
			last: '9999',
			none: '0',
			1: '1',
			2: '2',
			3: '3',
			4: '4',
			5: '5',
			6: '6',
			7: '7',
			8: '8',
			9: '9',
			10: '10',
			11: '11',
			12: '12',
		},
		outlineColor: ({ theme }) => theme('colors'),
		outlineOffset: {
			0: '0px',
			1: '1px',
			2: '2px',
			5: '5px',
			// Removed and added some values
		},
		outlineWidth: {
			0: '0px',
			1: '1px',
			2: '2px',
			5: '5px',
			// Removed and added some values
		},
		padding: ({ theme }) => theme('spacing'),
		placeholderColor: ({ theme }) => theme('colors'),
		placeholderOpacity: ({ theme }) => theme('opacity'),
		ringColor: ({ theme }) => ({
			DEFAULT: theme('colors.black', '#000'),
			...theme('colors'),
		}),
		ringOffsetColor: ({ theme }) => theme('colors'),
		ringOffsetWidth: {
			0: '0px',
			1: '1px',
			2: '2px',
			5: '5px',
			// Removed and added some values
		},
		ringOpacity: ({ theme }) => ({
			DEFAULT: '0.5',
			...theme('opacity'),
		}),
		ringWidth: {
			DEFAULT: '3px',
			0: '0px',
			1: '1px',
			2: '2px',
			5: '5px',
			// Removed and added some values
		},
		rotate: {
			0: '0deg',
			1: '1deg',
			2: '2deg',
			3: '3deg',
			6: '6deg',
			12: '12deg',
			45: '45deg',
			90: '90deg',
			180: '180deg',
		},
		saturate: {
			0: '0',
			50: '.5',
			100: '1',
			150: '1.5',
			200: '2',
		},
		scale: {
			0: '0',
			50: '.5',
			75: '.75',
			90: '.9',
			95: '.95',
			100: '1',
			105: '1.05',
			110: '1.1',
			125: '1.25',
			150: '1.5',
		},
		screens: {
			print: { raw: 'print' },
			// Removed and added some values
		},
		scrollMargin: ({ theme }) => ({
			...theme('spacing'),
		}),
		scrollPadding: ({ theme }) => theme('spacing'),
		sepia: {
			0: '0',
			DEFAULT: '100%',
		},
		skew: {
			0: '0deg',
			1: '1deg',
			2: '2deg',
			3: '3deg',
			6: '6deg',
			12: '12deg',
		},
		space: ({ theme }) => ({
			...theme('spacing'),
		}),
		spacing: {
			0: '0px',
			1: '1px',
			2: '2px',
			3: '3px',
			4: '4px',
			5: '5px',
			6: '6px',
			7: '7px',
			8: '8px',
			9: '9px',
			10: '10px',
			11: '11px',
			12: '12px',
			14: '14px',
			15: '15px',
			16: '16px',
			20: '20px',
			24: '24px',
			// Removed and changed some values
		},
		stroke: ({ theme }) => ({
			none: 'none',
			...theme('colors'),
		}),
		strokeWidth: {
			0: '0',
			1: '1',
			2: '2',
		},
		supports: {},
		data: {
			hover: 'hover="hover"',
		},
		textColor: ({ theme }) => theme('colors'),
		textDecorationColor: ({ theme }) => theme('colors'),
		textDecorationThickness: {
			auto: 'auto',
			'from-font': 'from-font',
			0: '0px',
			1: '1px',
			2: '2px',
			4: '4px',
			// Removed some values
		},
		textIndent: ({ theme }) => ({
			...theme('spacing'),
		}),
		textOpacity: ({ theme }) => theme('opacity'),
		textUnderlineOffset: {
			auto: 'auto',
			0: '0px',
			1: '1px',
			2: '2px',
			4: '4px',
			8: '8px',
		},
		transformOrigin: {
			center: 'center',
			top: 'top',
			'top-right': 'top right',
			right: 'right',
			'bottom-right': 'bottom right',
			bottom: 'bottom',
			'bottom-left': 'bottom left',
			left: 'left',
			'top-left': 'top left',
		},
		transitionDelay: {
			0: '0s',
			75: '75ms',
			100: '100ms',
			150: '150ms',
			200: '200ms',
			300: '300ms',
			500: '500ms',
			700: '700ms',
			1000: '1000ms',
		},
		transitionDuration: {
			DEFAULT: '150ms',
			0: '0s',
			75: '75ms',
			100: '100ms',
			150: '150ms',
			200: '200ms',
			300: '300ms',
			500: '500ms',
			700: '700ms',
			1000: '1000ms',
		},
		transitionProperty: {
			none: 'none',
			all: 'all',
			DEFAULT:
				'color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter',
			colors: 'color, background-color, border-color, text-decoration-color, fill, stroke',
			opacity: 'opacity',
			shadow: 'box-shadow',
			transform: 'transform',
		},
		transitionTimingFunction: {
			DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
			linear: 'linear',
			in: 'cubic-bezier(0.4, 0, 1, 1)',
			out: 'cubic-bezier(0, 0, 0.2, 1)',
			'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
		},
		translate: ({ theme }) => ({
			...theme('spacing'),
			'1/2': '50%',
			'1/3': '33.333333%',
			'2/3': '66.666667%',
			'1/4': '25%',
			'2/4': '50%',
			'3/4': '75%',
			full: '100%',
		}),
		width: ({ theme }) => ({
			auto: 'auto',
			...theme('spacing'),
			'1/2': '50%',
			'1/3': '33.333333%',
			'2/3': '66.666667%',
			'1/4': '25%',
			'2/4': '50%',
			'3/4': '75%',
			'1/5': '20%',
			'2/5': '40%',
			'3/5': '60%',
			'4/5': '80%',
			'1/6': '16.666667%',
			'2/6': '33.333333%',
			'3/6': '50%',
			'4/6': '66.666667%',
			'5/6': '83.333333%',
			'1/12': '8.333333%',
			'2/12': '16.666667%',
			'3/12': '25%',
			'4/12': '33.333333%',
			'5/12': '41.666667%',
			'6/12': '50%',
			'7/12': '58.333333%',
			'8/12': '66.666667%',
			'9/12': '75%',
			'10/12': '83.333333%',
			'11/12': '91.666667%',
			full: '100%',
			screen: '100vw',
			min: 'min-content',
			max: 'max-content',
			fit: 'fit-content',
		}),
		willChange: {
			auto: 'auto',
			scroll: 'scroll-position',
			contents: 'contents',
			transform: 'transform',
		},
		zIndex: {
			auto: 'auto',
			'-1': '-1',
			0: '0',
			1: '1',
			10: '10',
			20: '20',
			30: '30',
			40: '40',
			50: '50',
		},
	},
	plugins: [
		require('./assets/js/tailwindcss/group-focus-within.plugin.js'),
		require('./assets/js/tailwindcss/group-data-hover.plugin.js'),
	],
};
